export const cabFleet = {
  vehicles: [
    "Swift Dzire",
    "Kia Carrien",
    "Ertiga",
    "Innova Crysta",
    "13 Seater Tempo Traveller",
    "13 Seater SML",
    "Force 16 Seater Urbania",
    "17 Seater Tempo Traveller",
    "20 Seater Bus",
    "26 Seater Bus",
    "30 Seater Bus",
    "36 Seater Bus",
    "43 - 45 Seater Bus",
  ],

  luxuryVehicles: [
    "Innova Hycross",
    "Toyota Fortuner",
    "Mercedes S350",
    "Toyota Vellfire",
    "Kia Carnival",
    "Kia Carnival Limousine +",
    "Range Rover Sport HSE",
    "Audi A6",
    "Mercedes GLS350",
    "Mercedes E220",
    "Mercedes V220",
    "BMW E / S Class",
  ],
};